include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: info
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    # Mantenha temporariamente enquanto refatora:
    - lib/flutter_flow/**
    - lib/custom_code/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_dynamic_calls
    - avoid_returning_null_for_future
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_final_in_for_each
    - require_trailing_commas
    - sort_child_properties_last
    - unawaited_futures
    - use_key_in_widget_constructors
    - use_super_parameters
    - directives_ordering
    - prefer_single_quotes