// Domínios de e-mail temporário/descartável mais usados (bloqueados no
// cadastro). Lista curada a partir de github.com/disposable-email-domains —
// não é exaustiva: novos serviços surgem sempre, e a confirmação por e-mail
// continua sendo a garantia final. Subdomínios também são bloqueados
// (ex.: x.mailinator.com).

const DISPOSABLE_DOMAINS = new Set<string>([
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.co.uk",
  "20minutemail.com",
  "33mail.com",
  "anonbox.net",
  "burnermail.io",
  "byom.de",
  "chacuo.net",
  "cock.li",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "dispostable.com",
  "dropmail.me",
  "emailondeck.com",
  "emailfake.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "emailtemporario.com.br",
  "fakeinbox.com",
  "fakemail.net",
  "fakemailgenerator.com",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "inboxbear.com",
  "inboxkitten.com",
  "incognitomail.org",
  "jetable.org",
  "kasmail.com",
  "linshiyouxiang.net",
  "mail-temp.com",
  "mail.tm",
  "mail7.io",
  "mailcatch.com",
  "maildrop.cc",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailnesia.com",
  "mailpoof.com",
  "mailsac.com",
  "mailtemp.net",
  "mintemail.com",
  "mohmal.com",
  "moakt.com",
  "my10minutemail.com",
  "mytemp.email",
  "mytrashmail.com",
  "nada.email",
  "nowmymail.com",
  "one-time.email",
  "owlymail.com",
  "pokemail.net",
  "sharklasers.com",
  "spam4.me",
  "spambog.com",
  "spambox.us",
  "spamgourmet.com",
  "spamex.com",
  "temp-mail.io",
  "temp-mail.org",
  "tempail.com",
  "tempemail.net",
  "tempinbox.com",
  "tempmail.com",
  "tempmail.dev",
  "tempmail.net",
  "tempmail.plus",
  "tempmailo.com",
  "tempmailaddress.com",
  "tempr.email",
  "throwawaymail.com",
  "tmail.ws",
  "tmailor.com",
  "tmpmail.net",
  "tmpmail.org",
  "trash-mail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.me",
  "trashmail.net",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "zetmail.com",
]);

export function isDisposableDomain(domain: string): boolean {
  const d = domain.toLowerCase();
  if (DISPOSABLE_DOMAINS.has(d)) return true;
  // Subdomínios: "x.mailinator.com" → confere "mailinator.com".
  const parts = d.split(".");
  for (let i = 1; i < parts.length - 1; i++) {
    if (DISPOSABLE_DOMAINS.has(parts.slice(i).join("."))) return true;
  }
  return false;
}
