// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBI1G4JyfCQxGxZ8JawKXePboUxDiIUg',
    appId: '1:110350827168:web:605db3b3199bc2bda193c5',
    messagingSenderId: '110350827168',
    projectId: 'arcangel-4c066',
    authDomain: 'arcangel-4c066.firebaseapp.com',
    storageBucket: 'arcangel-4c066.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxg_qwkc14_IfL_DVv2Xq_36vjVswPHaI',
    appId: '1:110350827168:android:e7ae721586c82139a193c5',
    messagingSenderId: '110350827168',
    projectId: 'arcangel-4c066',
    storageBucket: 'arcangel-4c066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtocK_LaeE_HeEksGRDTJy0S6iFG5R6-c',
    appId: '1:110350827168:ios:47ee5d73303c3a5ea193c5',
    messagingSenderId: '110350827168',
    projectId: 'arcangel-4c066',
    storageBucket: 'arcangel-4c066.firebasestorage.app',
    iosClientId: '110350827168-9n07lul5t3097f8iedre195vgs9g16s0.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.arcangelooficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeBI1G4JyfCQxGxZ8JawKXePboUxDiIUg',
    appId: '1:110350827168:web:0f908e38de206148a193c5',
    messagingSenderId: '110350827168',
    projectId: 'arcangel-4c066',
    authDomain: 'arcangel-4c066.firebaseapp.com',
    storageBucket: 'arcangel-4c066.firebasestorage.app',
  );

}