// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyHDQs-RTm3J2oYolELIXKOYFWQE5ZEHQ',
    appId: '1:1004268647764:web:4253028bee32bacf6a84c1',
    messagingSenderId: '1004268647764',
    projectId: 'casoeuerre-8g1y00',
    authDomain: 'casoeuerre-8g1y00.firebaseapp.com',
    storageBucket: 'casoeuerre-8g1y00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhRLHN2sLMWfuvIjbnq72_tcHh9pBLT0E',
    appId: '1:1004268647764:android:a9d8c14596c133846a84c1',
    messagingSenderId: '1004268647764',
    projectId: 'casoeuerre-8g1y00',
    storageBucket: 'casoeuerre-8g1y00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhAtr3oQMG8d5uSN3HHj1gBqcxwBsu0j0',
    appId: '1:1004268647764:ios:951a636ef6b7c3676a84c1',
    messagingSenderId: '1004268647764',
    projectId: 'casoeuerre-8g1y00',
    storageBucket: 'casoeuerre-8g1y00.firebasestorage.app',
    androidClientId: '1004268647764-6eouss5sg9vvur7rho280137m9emaoad.apps.googleusercontent.com',
    iosClientId: '1004268647764-kfsb3a007ksmtp3b8q5mn23mnv1gsvvl.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.arcangelooficial',
  );
}
